# Generated by Django 5.0.3 on 2024-03-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Food category',
                'verbose_name_plural': 'Food categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='food item')),
                ('currently_registered', models.BooleanField(default=True, verbose_name='currently registered')),
                ('amount', models.IntegerField(default=0, verbose_name='food amount')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freezer_app.foodcategory')),
            ],
            options={
                'verbose_name': 'Food item',
                'verbose_name_plural': 'Food items',
            },
        ),
    ]
